HRMS/HRMS/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HRMS.Models;
using HRMS.Repository;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HRMS.Controllers
{
    public class MenuController : Controller
    {
        private readonly IConfiguration _iconfiguration;
        private readonly SqlConnection _con;
        private DBContextModel _db;
        private CommonR _objr;
        RoleSetupR objRole;
        public MenuController(IConfiguration configuration, DBContextModel db)
        {
            _iconfiguration = configuration;
            _con = new SqlConnection(_iconfiguration.GetConnectionString("DBConnection"));
            _db = db;
            // _objr = objr;
            // objRole = or;

        }

        public IActionResult Index()
        {
            try
            {
                return View(_db.MenuSetup.ToList());
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

        public IActionResult MenuPermission()
        {
            //RoleSetupR objRole = new RoleSetupR();
            //var roleList = new Tuple<IEnumerable<SelectListItem>>
            //        (objRole.getAllRole());
            //return View(roleList);

            ViewData["RoleId"] = new SelectList(_db.RoleSetup, "Id", "RoleName");
            return View();

        }
        [HttpPost]
        public JsonResult LoadMenu(int? Id)
        {
            int roleid = 1;
            try
            {
                List<MenuSetup> menu = new List<MenuSetup>();
                SqlCommand cmd = new SqlCommand("Select *from MenuSetup m inner join MenuPermission p on m.M_ID=p.MenuId where p.RoleId='" + roleid + "' and p.is_allow='Y'", _con);
                SqlDataAdapter da = new SqlDataAdapter(cmd);
                DataTable dt = new DataTable();
                da.Fill(dt);
                foreach (DataRow dr in dt.Rows)
                {
                    menu.Add(new MenuSetup
                    {
                        M_ID = Convert.ToInt32(dr["M_ID"]),
                        M_P_ID = Convert.ToInt32(dr["M_P_ID"]),
                        M_NAME = Convert.ToString(dr["M_NAME"]),
                        CONTROLLER_NAME = Convert.ToString(dr["CONTROLLER_NAME"]),
                        ACTION_NAME = Convert.ToString(dr["ACTION_NAME"]),
                        Area = Convert.ToString(dr["Area"]),

                    });
                }
                ViewBag.Menulist = menu;
                return Json(menu);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]
        public IActionResult MenuPermission(MenuPermission menu)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Delete()
        {

            return View();
        }

    }
}

HRMS/HRMS/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HRMS.Repository;
using Microsoft.Extensions.Configuration;
using HRMS.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using HRMS.ViewModel;

namespace HRMS.Controllers
{
    public class RoleController : BaseController
    {
        private readonly IConfiguration _iconfiguration;
        private readonly SqlConnection _con;
        private DBContextModel _db;
        public RoleController(IConfiguration configuration, DBContextModel db)
        {
            _iconfiguration = configuration;
            _con = new SqlConnection(_iconfiguration.GetConnectionString("DBConnection"));
            _db = db;

        }


        public IActionResult Index()
        {
            try
            {
                ViewBag.RoleList = _db.RoleSetup.ToList();

            }
            catch (Exception ex)
            {

                Alert(ex.Message, Repository.Enums.NotificationType.error);
            }

            return View();

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(RoleSetupViewModel roleSetup)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RoleSetup role = new RoleSetup();
                    role.RoleName = roleSetup.RoleName;
                    role.Status = roleSetup.Status;

                    _db.RoleSetup.Add(role);
                    _db.SaveChanges();
                }
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            try
            {
                var role = _db.RoleSetup.Where(x => x.Id == id).ToList();
                var response = role.FirstOrDefault();
               // return Json(response);
                return Json(response, new Newtonsoft.Json.JsonSerializerSettings());
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        [HttpDelete]
        public IActionResult Delete(int? Id)
        {
            try
            {
                var role = _db.RoleSetup.Where(x => x.Id == Id).FirstOrDefault();
                if (role != null)
                {
                    _db.RoleSetup.Remove(role);
                    _db.SaveChanges();
                }

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
    }
}

HRMS/HRMS/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using HRMS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace HRMS.Controllers
{
    public class UserController : Controller
    {
        private readonly IConfiguration _iconfiguration;
        private readonly SqlConnection _con;
        private DBContextModel _db;
        public UserController(IConfiguration configuration, DBContextModel db)
        {
            _iconfiguration = configuration;
            _con = new SqlConnection(_iconfiguration.GetConnectionString("DBConnection"));
            _db = db;

        }
        public IActionResult Index()
        {
            try
            {
                return View(_db.UserInfo.ToList());
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(UserInfo userInfo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserInfo user = new UserInfo();
                    user.UserId = userInfo.UserId;
                    user.FullName = userInfo.FullName;
                    user.RoleId = userInfo.RoleId;
                    user.ComId = userInfo.ComId;
                    user.Status = "Pending";
                    _db.UserInfo.Add(user);
                    _db.SaveChanges();
                }
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public IActionResult getRole()
        {
            ViewData["RoleId"] = new SelectList(_db.RoleSetup, "Id", "RoleName");
            return PartialView("_RoleId");
           
        }

        [HttpGet]
        public IActionResult Details(string uid)
        {
            try
            {
                var userdetails = _db.UserInfo.Where(x => x.UserId == uid).FirstOrDefault();
                return View(userdetails);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

HRMS/HRMS/Views/Shared/Components/UserMenu/Default.cshtml
@model IEnumerable<HRMS.Models.MenuSetup>
<!-- Sidebar Navigation -->
<ul class="sidebar-nav">

    @{foreach (var item in (Model.Where(m => m.M_P_ID == 0).GroupBy(obj => new { obj.M_ID }).Distinct().ToList()))
        {
            <li>
                @if (@item.FirstOrDefault().M_NAME == "Dashboard")
                {

                    <a href="/Dashboard/Index" class="sidebar-nav-menu">
                        <i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-cogwheel sidebar-nav-icon"></i>
                        <span class="sidebar-nav-mini-hide">@item.FirstOrDefault().M_NAME</span>

                    </a>
                }
                else
                {
                    <a href="#" class="sidebar-nav-menu">
                        <i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-cogwheel sidebar-nav-icon"></i>
                        <span class="sidebar-nav-mini-hide">@item.FirstOrDefault().M_NAME</span>

                    </a>
                    <ul>
                        @{foreach (var submenu in Model.Where(s => s.M_P_ID == item.FirstOrDefault().M_ID).ToList())
                            {
                                <li>
                                    <a href="/@submenu.CONTROLLER_NAME/@submenu.ACTION_NAME">@submenu.M_NAME</a>

                                    @*<ul>
                                            @{foreach (var action in Model.Where(a => a.M_P_ID == submenu.M_ID).ToList())
                                                {
                                                    <li>
                                                        <a href="/@action.CONTROLLER_NAME/@action.ACTION_NAME">
                                                            @action.M_NAME
                                                        </a>

                                                    </li>
                                                }

                                            }
                                        </ul>*@
                                </li>
                            }
                        }


                    </ul>

                }

            </li>
        }

    }

</ul>
<!-- END Sidebar Navigation -->
@*<!-- Sidebar Navigation -->
    <ul class="sidebar-nav">
        <li class="active">
            <a asp-area="Admin" asp-action="Index" asp-controller="Dashboard"><i class="gi gi-stopwatch sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
        </li>
        <li>
            <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-cogwheel sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Settings</span></a>
            <ul>
                <li>@Html.ActionLink("Menu Setup", "Index", "Menu")</li>
                <li>@Html.ActionLink("Menu Permission", "Index", "Menu")</li>
                <li>@Html.ActionLink("Users", "Index", "Authenticate")</li>
                <li>@Html.ActionLink("Company", "Index", "Company")</li>
                <li>@Html.ActionLink("Email Setup", "EmailInfo", "Setting")</li>
                <li>@Html.ActionLink("Role Setup", "RoleInfo", "Setting")</li>
            </ul>
        </li>

        <li>
            <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-package sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Catalog</span></a>
            <ul>
                <li>@Html.ActionLink("Add Product", "Create", "Product")</li>
                <li>@Html.ActionLink("Product List", "Index", "Product")</li>
            </ul>
        </li>

    </ul>

    <!-- END Sidebar Navigation -->*@
















@*<li>
        <a href="@Url.Action("Index", "Dashboard")" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-cogwheel sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>

    </li>*@
@*<li>
        <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-cogwheel sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Configuration</span></a>
        <ul>
            <li>@Html.ActionLink("Menu Setup", "Index", "Menu")</li>
            <li>@Html.ActionLink("Menu Permission", "Index", "Menu")</li>
            <li>@Html.ActionLink("Role Setup", "Index", "Role")</li>
            <li>@Html.ActionLink("Email Info", "EmailInfo", "Setting")</li>
            <li>@Html.ActionLink("User Info", "Index", "User")</li>
            <li>@Html.ActionLink("Company", "Index", "Company")</li>
        </ul>
    </li>*@